import { ref } from 'vue';
import type { Vote } from '~/types/vote';

export const useMockVotes = () => {
  return ref<Vote[]>([
    {
      id: 'vote-1',
      type: 'continuous',
      cellId: 'X[15][3]',
      row: 'Ecology — 74.2.COUNCIL',
      column: 'Average CO₂ emission level',
      proposedValue: 6.5,
      unit: 't/person/year',
      currentSample: [6.7, 6.5, 6.9, 7.1, 6.8],
      currentMean: 6.8,
      confidenceInterval: [6.5, 7.0],
      proposer: '0x1234...5678',
      timestamp: new Date('2025-11-20'),
      organ: 'Municipal Council #2 of Chelyabinsk Region',
      status: 'active',
      votesFor: 12,
      votesAgainst: 3,
      quorum: 15,
      participantsVoted: 15
    },
    {
      id: 'vote-2',
      type: 'categorical',
      cellId: 'Y[21][0]',
      row: 'Social Policy — 50.2.COUNCIL',
      column: 'Attitude towards basic income',
      proposedValue: 'needed',
      categories: ['needed', 'doubtful', 'dangerous'],
      currentSample: ['needed', 'doubtful', 'needed', 'dangerous'],
      currentDistribution: { 'needed': 0.50, 'doubtful': 0.25, 'dangerous': 0.25 },
      proposer: '0xabcd...efgh',
      timestamp: new Date('2025-11-22'),
      organ: 'Municipal Council #2 of Moscow Region',
      status: 'active',
      votesFor: 8,
      votesAgainst: 2,
      quorum: 10,
      participantsVoted: 10
    },
    {
      id: 'vote-3',
      type: 'continuous',
      cellId: 'X[18][2]',
      row: 'Information Policy — ASSEMBLY',
      column: 'Target size of OSINT team',
      proposedValue: 12,
      unit: 'people',
      currentSample: [10, 11, 12, 13, 12],
      currentMean: 11.6,
      confidenceInterval: [11, 12],
      proposer: '0x9999...1111',
      timestamp: new Date('2025-11-24'),
      organ: 'Party Congress',
      status: 'active',
      votesFor: 45,
      votesAgainst: 12,
      quorum: 50,
      participantsVoted: 57
    },
    {
      id: 'vote-4',
      type: 'categorical',
      cellId: 'Y[15][3]',
      row: 'Ecology — 74.2.COUNCIL',
      column: 'Assessment of landfill reclamation consequences',
      proposedValue: 'acceptable',
      categories: ['acceptable', 'doubtful', 'unacceptable'],
      currentSample: ['acceptable', 'acceptable', 'doubtful'],
      currentDistribution: { 'acceptable': 0.67, 'doubtful': 0.33, 'unacceptable': 0.00 },
      proposer: '0x7777...8888',
      timestamp: new Date('2025-11-23'),
      organ: 'Municipal Council #2 of Chelyabinsk Region',
      status: 'passed',
      votesFor: 18,
      votesAgainst: 2,
      quorum: 15,
      participantsVoted: 20
    }
  ]);
}
